apps/main/urls.py
from django.urls import path
from . import views

app_name='main'
urlpatterns=[
    path('',views.showblog,name="index"),
    path('registerblog/',views.create_blog,name="registerblog"),
    path('profile/',views.profile,name="profile"),
    path('infouser/<str:user_id>/',views.infouser,name="infouser"),
    path('article/<str:article_id>/',views.article_detail,name="article_detail"),
    path('profile/<str:article_id>/',views.article_detail,name="article_detail"),


]

templates/main_app/index.html
{% extends 'mainTemplates.html' %}



{%block body%}
<div class="row text-center" style="padding:75px;">
    {% comment %} <div class="row">
        {% for item in blogs %}
                <div class="col-4">
                    <div class="posts">
                        <img src="{{media_url}}{{item.main_img}}" alt="blog image" class="blogimg">
                        <p style="text-align:left; padding:10px;">{{item.blog_text| truncatewords:30}}</p>
                        <a href="{%url 'main:article_detail' item.blog_title %}">Read more</a>
                    </div>
                </div>
        {% endfor %}

    </div> {% endcomment %}
    {% for item in blogs %}
        <div class="col-4">
            <div class="posts">
                <a href="{%url 'main:article_detail' item.blog_title %}">
                    <img src="{{media_url}}{{item.main_img}}" alt="blog image" class="blogimg">
                    <p style="text-align:left; padding:10px;">{{item.blog_text| truncatewords:30}}</p>
                </a>
                <a href="{%url 'main:article_detail' item.blog_title %}">Read more</a>
                <a href="{%url 'main:infouser' item.user_registered.email %}">
                    <div class="row" style="padding:10px 0px 20px 50px;">
                        <img src="{{item.user_registered.image_url}}" width="50px" height="50px" alt="" style="border-radius: 50px;">
                        <i style="margin:10px">{{item.user_registered.email}}</i>
                    </div>
                </a>
            </div>


            
        </div>
    {% endfor %}
</div>

{%endblock body%}

templates/main_app/mainblog.html
{% extends 'mainTemplates.html' %}

{% block body %}
        <div class="body_size container">
            <div>
                <div>
                    <img src="{{media_url}}{{article.main_img}}" width="100%" height="300px">
                </div>
                <div>
                    <h1>
                        {{article.blog_title}}
                    </h1>
                </div>
                <div>
                    <p class="blog-p">
                        {{article.blog_text}}
                    </p>
                </div>
            </div>
            <div>
                <div class="row" style="padding:10px 0px 20px 50px;">
                    <img src="{{article.user_registered.image_url}}" width="50px" height="50px" alt="" style="border-radius: 50px;">
                    <i style="margin:10px">{{article.user_registered.email}}</i>
                </div>
            </div>
        </div>
    
{% endblock body %}

templates/main_app/profile.html
{% extends 'mainTemplates.html' %}
{%block body%}
<div class=" text-center" style="margin:75px;">
    <div>
        <div  class="row" style="margin:20px 25px;">
            <div style="margin:0px 20px 0px 0px;">
            <img src="{{info.image_url}}" alt="" width="300px" height="300px" >
            </div>
            <div>
                <h1 style="margin-top:50px;">{{info.email}}</h1>
            </div>
        </div>
        
    </div>

    <div class="row text-center" style="margin:20px 100px 20px 100px; border:1px solid gray;"></div>


    <div class="row">
        {% for item in blogs %}
                <div class="col-4">
                    <div class="posts">
                        <a href="{%url 'main:article_detail' item.blog_title %}">
                            <img src="{{media_url}}{{item.main_img}}" alt="blog image" class="blogimg">
                            <p style="text-align:left; padding:10px;">{{item.blog_text| truncatewords:30}}</p>
                        </a>
                        <a href="{%url 'main:article_detail' item.blog_title %}">Read more</a>
                    </div>
                </div>
        {% endfor %}

    </div>

</div>

{%endblock body%}

templates/main_app/register_blog.html
{% extends 'mainTemplates.html' %}



{% block body %}
<div class="body_size" >
    <form method="post"  enctype="multipart/form-data" >
        {% csrf_token %}
        <section class="d-flex justify-content-around align-items-center" style="width:100%;">
            <div>
                {{form.as_p}}
            </div>
            <div>
                <img src="{{media_url}}/image/logo/2-2.png" alt="" width="400px">
            </div>
        </section>
        <div class="d-flex">
            <input type="submit" value="create" class="btn btn-success btn-block " style="width:150px !important; margin:10px 10px 50px 200px">        
        </div>
    </form>
</div>

{% endblock body %}