apps/account/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns=[
    path('register/',views.RegisterUserView.as_view(),name="register"),
    path('login/',views.LoginUserView.as_view(),name="login"),
    path('logout/',views.LogoutUserView.as_view(),name="logout"),
] 

apps/main/urls.py
from django.urls import path
from . import views

app_name='main'
urlpatterns=[
    path('',views.showblog,name="index"),
    path('registerblog/',views.create_blog,name="registerblog"),
    path('profile/',views.profile,name="profile"),
    path('infouser/<str:user_id>/',views.infouser,name="infouser"),
    path('article/<str:article_id>/',views.article_detail,name="article_detail"),
    path('profile/<str:article_id>/',views.article_detail,name="article_detail"),


]

templates/pertials/footer.html
<div class="row justify-content-center m-0">
    <div class="col-md-5 text-center">
        <p>
            tel: +21 21000 0000
            <br> 
            mail: gmail@gmail.com
            <br>
            <a href="#"><i class="fab fa-twitter-square"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook-square"></i></a>
            <a href="#"><i class="fab fa-youtube-square"></i></a>
            <hr class="footer-hr">
            <i style="font-size:20px">Do not hesitate to contact us </i>
        </p>
    </div>
</div>
</div>

templates/pertials/messages.html
{% if messages%}
    {%for message in messages%}
    <h5 class="alert alert-{{message.tags}}" style="margin-top: 70px;">
        {{message}}
    </h5>
    {%endfor%}
{%endif%}

templates/pertials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    {%if user.is_authenticated %}
        <a href="{%url 'main:profile'%}" class="navbar-brand">
            <img src="{{info.image_url}}" alt="logo" width="40" height="40" style="border-radius:50px;">
        </a>
        <a class="navbar-brand" href="{%url 'main:profile'%}">{{info.email}}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    {%else%}
        <a href="{%url 'main:index'%}" class="navbar-brand">
            <img src="../../media/image/logo/1.webp" alt="logo" width="30" height="30">
        </a>
        <a class="navbar-brand" href="{%url 'main:index'%}">Portal Web</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    {%endif%}


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'main:index'%}">Home</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            {%if user.is_authenticated %}
                <li class="nav_item active"><a class="nav-link" href="{%url 'main:registerblog'%}">Create Post<span class="sr-only">(current)</span></a></li>
                <li class="nav_item active"><a class="nav-link" href="{%url 'main:profile'%}">Profile<span class="sr-only">(current)</span></a></li>
                <li class="nav_item active"><a class="nav-link" href="{% url 'accounts:logout'%}">Log out<span class="sr-only">(current)</span></a></li>

            {%else%}
                <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:login'%}">Log in<span class="sr-only">(current)</span></a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'accounts:register'%}">Register<span class="sr-only">(current)</span></a></li>
            {%endif%}
        </ul>
    </div>
</nav>

templates/pertials/script.html
<script src="js/jquery.min.3.3.1.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/script.js"></script>